Index:
    path: /
    controller: App\Controller\TestController::Index
IndexResponse:
    path: /Response
    controller: App\Controller\TestController::IndexResponse
IndexRedirect:
    path: /Redirect
    controller: App\Controller\TestController::IndexRedirect
IndexRedirectRoute:
    path: /RedirectRoute
    controller: App\Controller\TestController::IndexRedirectToRoute
IndexRender:
    path: /Render
    controller: App\Controller\TestController::IndexRender
IndexJSON:
    path: /JSON
    controller: App\Controller\TestController::IndexJSON
