Index:
    path: /
    controller: App\Controller\TestController::Index
Index:
    path: /Response
    controller: App\Controller\TestController::IndexResponse
Index:
    path: /Redirect
    controller: App\Controller\TestController::IndexRedirect
Index:
    path: /RedirectRoute
    controller: App\Controller\TestController::IndexRedirectToRoute
Index:
    path: /Render
    controller: App\Controller\TestController::IndexRender
